import type { CatalogCollections } from "@/lib/types";
import { createDefaultStackVersion } from "@/lib/fence/stackVersions";

/** Dane demo gdy Firebase nie jest skonfigurowany (dev bez .env.local). */
export const MOCK_CATALOG: CatalogCollections = {
  posts: [
    {
      id: "post-1",
      name: "Słupek standard",
      slug: "standard",
      widthCm: 20,
      sortOrder: 0,
      active: true,
    },
    {
      id: "post-2",
      name: "Słupek dekoracyjny",
      slug: "dekor",
      widthCm: 25,
      sortOrder: 1,
      active: true,
    },
  ],
  fenceBlocks: [
    {
      id: "block-a",
      name: "Panel A",
      heightCm: 50,
      role: "standard",
      patternKey: "concrete-standard",
      supportsAzurowosc: true,
      sortOrder: 0,
      active: true,
    },
    {
      id: "block-b",
      name: "Panel B",
      heightCm: 25,
      role: "standard",
      patternKey: "concrete-standard",
      supportsAzurowosc: true,
      sortOrder: 1,
      active: true,
    },
    {
      id: "block-cap",
      name: "Panel falowany",
      heightCm: 25,
      role: "cap",
      patternKey: "concrete-arch",
      supportsAzurowosc: false,
      sortOrder: 2,
      active: true,
    },
  ],
  azurowoscPresets: [
    {
      id: "azur-2",
      name: "Ażur 2 cm",
      gapCm: 2,
      sortOrder: 0,
      active: true,
    },
    {
      id: "azur-6",
      name: "Ażur 6 cm",
      gapCm: 6,
      sortOrder: 1,
      active: true,
    },
    {
      id: "azur-8",
      name: "Ażur 8 cm",
      gapCm: 8,
      sortOrder: 2,
      active: true,
    },
  ],
  fenceVariants: [
    {
      id: "variant-a",
      name: "Panel A",
      postId: "post-1",
      stack: [{ blockId: "block-a", mode: "repeat" }],
      stackVersions: [
        {
          id: "variant-a-v-a",
          name: "Wersja A",
          stack: [{ blockId: "block-a", mode: "repeat" }],
          azurowoscEnabled: false,
          azurowoscOptions: [],
          sortOrder: 0,
        },
        {
          id: "variant-a-v-b",
          name: "Wersja B",
          stack: [{ blockId: "block-a", mode: "repeat" }],
          azurowoscEnabled: true,
          azurowoscOptions: [
            { gapCm: 10, layouts: [] },
            { gapCm: 50, layouts: [] },
          ],
          azurowoscColorId: "c-1",
          sortOrder: 1,
        },
      ],
      azurowoscEnabled: false,
      azurowoscPresetId: null,
      heightIds: ["h-3", "h-4"],
      sectionWidthCm: 200,
      sortOrder: 0,
      active: true,
    },
    {
      id: "variant-b-cap",
      name: "Panel B + falowany",
      postId: "post-1",
      stack: [
        { blockId: "block-cap", mode: "once" },
        { blockId: "block-b", mode: "repeat" },
      ],
      stackVersions: [
        createDefaultStackVersion(0, {
          id: "variant-b-v-a",
          name: "Wersja A",
          stack: [
            { blockId: "block-cap", mode: "once" },
            { blockId: "block-b", mode: "repeat" },
          ],
          azurowoscEnabled: true,
          azurowoscOptions: [{ gapCm: 8, layouts: [] }],
          azurowoscColorId: "c-1",
          postHeightOffsetCm: -25,
          sortOrder: 0,
        }),
      ],
      azurowoscEnabled: true,
      azurowoscPresetId: null,
      azurowoscOptions: [{ gapCm: 8, layouts: [] }],
      azurowoscColorId: "c-1",
      heightIds: ["h-4"],
      sectionWidthCm: 200,
      sortOrder: 1,
      active: true,
    },
  ],
  fenceBlockTextures: [
    {
      id: "fbt-1",
      blockId: "block-a",
      colorId: "c-1",
      imageUrl: "",
      priceNetPerUnit: 150,
    },
    {
      id: "fbt-2",
      blockId: "block-a",
      colorId: "c-2",
      imageUrl: "",
      priceNetPerUnit: 175,
    },
    {
      id: "fbt-3",
      blockId: "block-b",
      colorId: "c-1",
      imageUrl: "",
      priceNetPerUnit: 90,
    },
    {
      id: "fbt-4",
      blockId: "block-cap",
      colorId: "c-1",
      imageUrl: "",
      priceNetPerUnit: 120,
    },
  ],
  heights: [
    { id: "h-1", label: "1,00 m", valueM: 1.0, sortOrder: 0, active: true },
    { id: "h-2", label: "1,50 m", valueM: 1.5, sortOrder: 1, active: true },
    { id: "h-3", label: "1,75 m", valueM: 1.75, sortOrder: 2, active: true },
    { id: "h-4", label: "2,00 m", valueM: 2.0, sortOrder: 3, active: true },
    { id: "h-5", label: "2,25 m", valueM: 2.25, sortOrder: 4, active: true },
  ],
  colors: [
    {
      id: "c-1",
      name: "Szary naturalny",
      hex: "#9ca3af",
      sortOrder: 0,
      active: true,
    },
    {
      id: "c-2",
      name: "Antracyt",
      hex: "#374151",
      sortOrder: 1,
      active: true,
    },
    {
      id: "c-3",
      name: "Biały",
      hex: "#f3f4f6",
      sortOrder: 2,
      active: true,
    },
    {
      id: "c-4",
      name: "Piaskowy",
      hex: "#d6c4a8",
      sortOrder: 3,
      active: true,
    },
    {
      id: "c-5",
      name: "Grafit",
      hex: "#4b5563",
      sortOrder: 4,
      active: true,
    },
    {
      id: "c-6",
      name: "Czerwony cegła",
      hex: "#b45309",
      sortOrder: 5,
      active: true,
    },
  ],
  elements: [
    {
      id: "gate-1",
      type: "brama",
      name: "Brama dwuskrzydłowa",
      sortOrder: 0,
      active: true,
      priceNet: 4500,
    },
    {
      id: "wicket-1",
      type: "furtka",
      name: "Furtka standard",
      sortOrder: 0,
      active: true,
      priceNet: 1200,
    },
  ],
  postTextures: [
    {
      id: "pt-1",
      postId: "post-1",
      colorId: "c-1",
      imageUrl: "",
      priceNetPerPost: 80,
    },
    {
      id: "pt-2",
      postId: "post-1",
      colorId: "c-2",
      imageUrl: "",
      priceNetPerPost: 95,
    },
  ],
  spacerOptions: [],
  panels: [],
  panelTextures: [],
};